### ISSUE TITLE
更新后刷新显示 错误：result is not defined

### ISSUE THREAD

**Issue by IntheAlley** [OpaqueGlass/listChildDocs#11]
即使删除挂件后再重新下载并且重新放置挂件后刷新依旧显示 result is not defined

**Comment by OpaqueGlass** [comment]
使用`ctrl + shift +i`可以打开开发者工具，麻烦在错误发生后截屏`控制台`里面的内容，谢谢。

**Comment by OpaqueGlass** [comment]
已定位到问题，我尽快更新，谢谢反馈。

**Comment by OpaqueGlass** [comment]
如果可以的话，帮忙测试一下，谢谢：
[listChildDocs-dev.zip](https://github.com/OpaqueGlass/listChildDocs/files/9591337/listChildDocs-dev.zip)

**Comment by IntheAlley** [comment]
功能已经可以正常实现了 不好意思才看到

**Comment by IntheAlley** [comment]
*用的这个dev版本可以正常实现功能

**Comment by OpaqueGlass** [comment]
好的，谢谢回复，这个版本已经申请上传到集市了，再次感谢反馈。
