### ISSUE TITLE
【反馈】【功能请求】支持网页访问，图标显示，界面美化

### ISSUE THREAD

**Issue by olunju** [OpaqueGlass/listChildDocs#12]
##【反馈】

~1. 不支持网页访问~

~网页上点击链接想进入文档，会提示打开应用~

> 更改模式就可以了

2. 图标是默认图标

目录中显示的是默认图标，而对应的文档是有改过图标的

![image](https://user-images.githubusercontent.com/67050602/190945374-0009642e-2b91-4e7f-8d0d-f3c75221136c.png)

## 【请求】

1. 自动高度，不用手动调整高度，因为原生滚动条和思源的不契合

2. 界面美化下，例如加个带底色的工具栏，图标的颜色太鲜艳了，刷新按钮的边框有点违和

![image](https://user-images.githubusercontent.com/67050602/190945610-ab90de29-c41c-4b52-a142-355526f53dba.png)

**Comment by OpaqueGlass** [comment]
1. p.s.`挂件beta`下悬停在链接上会弹出悬浮窗，悬浮窗只能在鼠标离开挂件或手动点击才会关闭，如果不需要，请打开`${思源data目录}\widgets\listChildDocs\src\config.js`设定`floatWindowEnable`为`false`；
2. 请问使用的是原生的emoji图标吗？这种情况理论上是可以显示的，可能需要麻烦你提供一下选择的emoji图标我再试试；
如果是自定义的emoji，请在阅读README.md“注意”部分后，选择是否要启用`customEmojiEnable`（在`config.js`中更改为`true`）；
![image](https://user-images.githubusercontent.com/52985952/190955336-4cbc87a2-27c9-474c-ab8d-ec743b8ca8fd.png)

3. #13
4. 麻烦描述的再清晰些，目前外观我觉得还凑合😖，可能不会有很大的变动；
  4.1. 带底色的工具栏是指？能否举个例子？p.s.不会设计UI，这个变动我可能做不了
  4.2. 是刷新、设置图标颜色太鲜艳了吗？直接改成深一点的颜色能解决吗？
  4.3. 去掉刷新按钮边框更好吗？

> 如果确定进行大幅度外观变更，预计10月推进；

**Comment by olunju** [comment]
1. 图标是自定义的，不是原生的。

![image](https://user-images.githubusercontent.com/67050602/190979861-05ba5982-e04e-476e-974d-9152ca206ded.png)

2. 底色是我的建议，不过我发现不同的主题下有不同的表现效果，目前我挺满意的，见下图。

> 看一下我试着换了2个图标，加了一一个文本，主题 onenote 下的效果

![image](https://user-images.githubusercontent.com/67050602/190999972-7123c31f-bc16-4c81-ada2-09448f0e931e.png)

主要还是自定义图标的问题啦，外观都是次要的

**Comment by OpaqueGlass** [comment]
1. 自定义的emoji文档图标理论上可以显示的，按下图操作

![image](https://user-images.githubusercontent.com/52985952/191003058-d729e110-c443-4364-a945-3a35da61bc2d.png)

>  ![image](https://user-images.githubusercontent.com/67050602/190999972-7123c31f-bc16-4c81-ada2-09448f0e931e.png)

在文档里面的话，这里的图标一个来自于主题，一个来自于挂件写进去的emoji。挂件v0.0.7应该可以将自定义emoji作为图片插入的，如下。（图片的效果不太好，插入到文档中有边距）

![image](https://user-images.githubusercontent.com/52985952/191002459-fd7a7294-3af6-4cea-8fdc-121a3f8bcdc5.png)
![image](https://user-images.githubusercontent.com/52985952/191002487-6aafb7a1-0659-4ee4-ab05-63d184d619ca.png)
![image](https://user-images.githubusercontent.com/52985952/191001897-ae658b76-2891-4f25-bb6c-9727214556be.png)


3. 按钮这块儿我再想想，下个版本要不就只留个图标（全黑的按钮图标（png）在夜间模式下显示效果不知道怎么样，就没敢用😖）。

**Comment by olunju** [comment]
谢谢，改了 customEmojiEnable 为 true 后生效了，不过发现了个不方便的地方，就是生成内容后，设置的内容不会保存，表现如下：生成 3 层级的树结构。下次进来手动刷新就会变为 1 层级了。

**Comment by OpaqueGlass** [comment]
设置之后需要双击刷新按钮保存，请问双击了吗？

> 一开始设定为手动保存是为了减少设定挂件属性的次数，没加单独的按钮是不想html、css上面折腾了😆
> p.s. 我记得README.md里面写了

**Comment by olunju** [comment]
我的
