### ISSUE TITLE
默认创建报错，修改默认展示风格为URL或者引用块

### ISSUE THREAD

**Issue by HecterF** [OpaqueGlass/listChildDocs#16]
每次创建后，默认的都报错。

![VLQ)0S8Z T`$8Z$)MS @O 0](https://user-images.githubusercontent.com/46716553/193416644-bd661a4a-f3cf-4350-be5d-2ccc04427240.png)

建议：
1. 将默认模式设置为以下方式
2. 默认不要用无序列表，用有序列表展示更方便查看笔记的总条数。

![image](https://user-images.githubusercontent.com/46716553/193416690-8fd81444-7bd0-42c3-a61a-e18f1ed7f821.png)

**Comment by OpaqueGlass** [comment]
感谢关注，

1. 在所有模式下，刚创建挂件时均存在“获取属性失败”错误提示，此错误提示不打算移除。
如果您说的是“Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.”，下一版修复，请关注 #15 。

> 挂件初始化时必须读取属性加载设置（否则设置项将无法读入），在刚创建挂件时，数据库中无该挂件的属性信息，因而请求属性失败，挂件报错；
> 考虑到正常使用中也可能请求属性失败，此错误信息没有被我忽略。如果您在创建挂件之外的其他情况遇见此问题，请向我反馈。
> url、引用块模式下，创建挂件时也存在此错误提示。由于重设挂件高度在获取属性之后，错误提示被隐藏，这是个bug；

2. 默认设置可在`config.js`自行修改，我暂无计划更改下载集市包时的默认设置，另请参考README.md和config.js开头的配置说明；
在同步启用时，自动刷新并不安全，且刚创建挂件时，相关信息不完整，无法进行自动刷新。请您理解，启用自动刷新不能作为默认设置。

![image](https://user-images.githubusercontent.com/52985952/193433535-71a454b2-90c1-42e5-9d23-73552a85fdc7.png)


3. 感谢提议，请关注issue #17（需要点时间，预计下一版不会发布）。

**Comment by OpaqueGlass** [comment]
由于您长时间未回复，此issue先关闭了。如有疑问，请在此issue回复；如有其他bug反馈，请另开issue，谢谢。

**Comment by OpaqueGlass** [comment]
文档内有序列表方式现在在测试。您可以下载测试版参与测试（模式名称以`1.`开头），如有问题请反馈，谢谢。

https://github.com/OpaqueGlass/listChildDocs/releases/tag/v0.0.9-b1

说明：有序列表在文档中写入时，序号样式依赖于主题的有序列表显示。

关于默认项我再想一下，看样子将默认值选为挂件内好像不是很多人能接受/(ㄒoㄒ)/~~
