### ISSUE TITLE
feat. 支持挂件内分列

### ISSUE THREAD

**Issue by zhang-hao-me** [OpaqueGlass/listChildDocs#2]
![屏幕截图 2022-08-26 161357](https://user-images.githubusercontent.com/83968146/186855908-3865aaf1-b1f8-4523-b882-39e220680011.jpg)
分列的功能不起作用，选了5列但是只排成一列

**Comment by OpaqueGlass** [comment]
你好，
1.你说的是像word一样的分栏吗？目前不支持。如果需要，我有空会看一下要怎么实现。
2.图中的设置设定的是展示的子文档深度/层级，就是要不要显示子文档的子文档，设置项说明详见README。如果是更深层级的子文档无法展示，麻烦`ctrl+alt+I`看一下输出。

> P.S.之前用邮件回复了一次好像没发出来。

> ![屏幕截图 2022-08-26 161357](https://user-images.githubusercontent.com/83968146/186855908-3865aaf1-b1f8-4523-b882-39e220680011.jpg) 分列的功能不起作用，选了5列但是只排成一列

**Comment by zhang-hao-me** [comment]
就是分列的功能，我以为是bug呢

**Comment by OpaqueGlass** [comment]
ok，我看看怎么实现。挂件内好说，css就行，就是可能要手动到配置文件或者挂件属性里改分列数（我个人不想增加挂件上的选项了）。要建立文档内超级块可能比较麻烦。

挂件内
- [x] css实现分列
- [ ] 合适的分列控制方法/UI

文档中
- [ ] 确定可行性

**Comment by OpaqueGlass** [comment]
@zhang-hao-me 像下面这样的分列可以接受吗？另外，关于分列设置方式有什么其他建议？
![a1](https://user-images.githubusercontent.com/52985952/187057859-25284f2a-4f92-43d9-ad14-3ee49fca882c.png)
