### ISSUE TITLE
是否考虑将WordCounter的功能集成进ListChildDocs中

### ISSUE THREAD

**Issue by pokerLL** [OpaqueGlass/listChildDocs#20]
就是集市挂件中的WordCounter挂件，可以统计当前文档下总字数，总段落数以及所有笔记的字数，页数。
那个也是需要手动刷新  感觉两个集成到一起蛮好的 希望作者考虑一下

**Comment by OpaqueGlass** [comment]
应该不会考虑，谢谢反馈。如果考虑加入，会重开此issue。
一次刷新两个内容固然很好，但我觉得这是两个独立的功能；思源也已经支持统计当前文档的文字数量，在窗口下方。

另外，listChildDocs支持打开文档时自动刷新（文档数量过多可能刷新时间会变长），在挂件内勾选自动刷新，然后双击刷新按钮保存设置；WordCounter好像也有自动刷新选项；

> 注：
> 为了保证不会发生同步冲突或同步覆盖，默认禁止对文档中的目录进行自动刷新；
> 如果不使用同步，可以考虑关闭安全模式；详细请阅读README.md；
