### ISSUE TITLE
是否考虑支持全局所有文档的ListChildDoc

### ISSUE THREAD

**Issue by pokerLL** [OpaqueGlass/listChildDocs#21]
就是将笔记本也涵盖在内 将笔记本作为二级，虚拟一个根作为一级，其他再是文档这样子 
因为现在笔记多了每次要先打开笔记本 然后点开几级文档才好找到要用的文档
如果能和主题结合  直接放在启动页面(就是不打开任何文档显示的页面)就更好了
希望作者考虑一下

**Comment by OpaqueGlass** [comment]
####  关于提议1：
可以有，但我最近在忙别的事，目前也卡着有序列表没有测试完，发布了这个有序列表之后再安排，预计12月之后；
另外，为何要虚拟一个根作为第一层级呢？按照我的理解大纲目录就是下面这样：

- 笔记本1
- 笔记本2
  - 文档1
- 笔记本3

> 但请注意：文档很多的话，刷新（生成）文档目录会很花时间的，这可能也是文档树没有默认全部展开功能的原因。

#### 关于提议2：
和主题结合不太可能，我不了解这个的实现方式，您可以考虑以下方法替代：
打开 设置--文档树--启动时关闭所有页签功能，然后钉住一个文档作为启动页，在这个文档中插入挂件；由于启动时会保留未钉住的页签，这个文档应该会在启动时打开；

**Comment by OpaqueGlass** [comment]
hi, [v0.1.0-b1](https://github.com/OpaqueGlass/listChildDocs/releases/tag/v0.1.0-b1)现已支持从笔记本上级创建子文档目录，版本为内测版，暂不发布到集市，如果可以，请下载测试一下，谢谢。
【测试版不要替代原有挂件，请小范围测试】。
目录结构如下：
- 开启的笔记本1
  - 笔记本内文档1
  - 笔记本内文档2
- 开启的笔记本2
  - 笔记本内文档1
  - 笔记本内文档2
- 开启的笔记本3
  - 笔记本内文档1
  - 笔记本内文档2

但请注意：
1. 层级数选定过大会导致刷新缓慢；
2. 在挂件中列出子文档，由于每次打开需要刷新，会导致体验下降；
3. 在文档中列出子文档，由于子文档目录在同一个无序/有序列表下，列表过长可能导致文档加载缓慢。

**Comment by pokerLL** [comment]
get

**Comment by pokerLL** [comment]
在2.4.12和2.5.3两个版本上使用了一天，暂时没有什么问题出现

**Comment by OpaqueGlass** [comment]
ok 谢谢反馈😀
