### ISSUE TITLE
增加配置项隐藏刷新按钮

### ISSUE THREAD

**Issue by pokerLL** [OpaqueGlass/listChildDocs#29]
我的使用场景是固定了一个文档做全局目录，但由于每个笔记本下的内容不同-每个笔记本需要的层级深度也不同，因此全局目录实际上需要经过我的二次修改，这时如果点了刷新就会覆盖掉我的修改，不过在其他场景下每次点进一个文档我都会先点一下刷新按钮来刷新内容，所以看看有没有什么优雅的方式能解决这两个场景之间的冲突。

一种可能性：增加配置项，将刷新按钮移入 `显示/隐藏设置` 下。

**Comment by OpaqueGlass** [comment]
呃，是因为在其他场景习惯了点刷新所以在全局目录的场景也会顺手点刷新吗？
这要做的话得保存在挂件属性里面，感觉挺冗余的。不同步的话，其他场景下改成自动刷新吧🧐

**Comment by OpaqueGlass** [comment]
emm，我觉得不太好看。下次发测试版的时候麻烦测试一下，谢谢。

![image](https://user-images.githubusercontent.com/52985952/210677227-81eeb13d-fd9f-4d4b-9a36-68bdee71b402.png)
P.S.只在加载时处理，修改选项之后双击刷新按钮保存，然后重新打开文档。
加载挂件的时候刷新按钮还是一闪而过😅

**Comment by pokerLL** [comment]
新版本测试：
其实还好，我试了一下不加这个隐藏的情况下，上面那一块在首次加载文档时还是会闪一下，区别不是很大

关于改成自动刷新：
目前正在尝试

**Comment by OpaqueGlass** [comment]
ok👌，那这个修改先保留。
另外，这里是改成自动刷新的补充说明（主要是在同步失败时可能会覆盖）：https://github.com/OpaqueGlass/listChildDocs/blob/dev/about_auto_refresh.md

> 这个版本里 创建列表块时加属性 的功能也加上了。配置之后，每个挂件都加属性，emm，每个块都会先变成导图。

**Comment by pokerLL** [comment]
其实我对于自动刷新的时机不是很理解，可以解释一下吗

**Comment by OpaqueGlass** [comment]
（前提是config.js里 `safeMode`为`false`）
从文档树打开文档 和 windows页签切换到文档的时候。

**Comment by pokerLL** [comment]
开启自动刷新后整个挂件都会闪一下，体验不是很好，因此我可能更倾向于手动刷新

**Comment by pokerLL** [comment]
或者在目前的基础上将自动刷新时机也做成配置项会不会更好一点-就我个人而言我只需要在首次打开文档的时候一定刷新一次，但是页签切换时也刷新就会出现上面闪眼睛的情况，不知道思源技术上能不能实现

**Comment by OpaqueGlass** [comment]
> 开启自动刷新后整个挂件都会闪一下，体验不是很好，因此我可能更倾向于手动刷新

你说的是哪个啊，麻烦再描述一下？挂件开不开自动刷新都闪吧（挂件高度会先长再变短，这个不太好办），要是列表转导图闪的话，可能可以优化，我试试。

> 或者在目前的基础上将自动刷新时机也做成配置项会不会更好一点-就我个人而言我只需要在首次打开文档的时候一定刷新一次，但是页签切换时也刷新就会出现上面闪眼睛的情况，不知道思源技术上能不能实现

页签切换时自动刷新可以关，在`config.js`把`includeOS`改为`[]`，下个版本要不把includeOs改到setting里面~

```javascript
let includeOs = [];//监视页签变化自动刷新功能将在列出的操作系统上启用
```

**Comment by pokerLL** [comment]
1. 之前的闪动说的是下面的内容块闪动 现在换了新版本没有了（明天去公司了可以再测一下看看是什么导致的） 使用感觉良好
2. widgets目录下的custom.js配置目前使用没有问题
3. 首次创建挂件时如果不点刷新则自动刷新会触发（提示文字会变化）但是不会生成内容，不知道是不是bug

**Comment by OpaqueGlass** [comment]
ok，谢谢~
关于3. ：挂件会把目录插入在挂件下方。之前思源在刚插入挂件的时候找不到这个位置、会导致状态异常，现在的版本好像没这个问题了，我改一下。
