### ISSUE TITLE
挂件强制重置配置

### ISSUE THREAD

**Issue by pokerLL** [OpaqueGlass/listChildDocs#31]
目前有一个场景，因为我基本所有目录都是使用的同一个配置，有的时候会发现目前使用的方式需要改进（例如这次将所有内容块的方式改为挂件内），但是需要一个个去手动删除然后重新添加，特别麻烦。

所以我想在加载挂件的时候有没有可能我们通过一个配置项（或者在设置中添加一个选项）强制挂件去加载默认配置覆盖掉之前的配置，当不需要的时候我们再把这个配置项改回去就好。

其实最理想的情况是自动寻找重置所有挂件，但以我的前端知识来看这个好像不太能实现并且会带有性能和卡顿的问题。所以我更多考虑的是第一个方式。

作者大大可以看看这个有没有实现的必要，工作顺利！

**Comment by OpaqueGlass** [comment]
ok，谢谢建议，目前是按照方式1实现的-->[listChildDocs-dev#31.zip](https://github.com/OpaqueGlass/listChildDocs/files/10533529/listChildDocs-dev.31.zip)

- 强制加载默认配置是对所有挂件都生效的。如果有一些挂件不需要重载配置，避免打开所在文档，或者在`overwriteOrRemoveWhiteDocList`把对应的文档id加上；
- 加载默认配置需要加载挂件，也就是需要浏览一遍所有挂件所在的文档；

**Comment by pokerLL** [comment]
使用状况良好，目前没有发现问题。辛苦了~

**Comment by OpaqueGlass** [comment]
好的，ヾ(•ω•`)o
