### ISSUE TITLE
挂件调整后，退出思源会恢复初始设置

### ISSUE THREAD

**Issue by loudawang** [OpaqueGlass/listChildDocs#36]
您好，您这个插件非常赞。就是目前我遇到一个问题。
我会进行 分成2列，3个层级的操作。每次操作完后，退出思源，再次打开，就会变成默认的1列1层。

**Comment by pokerLL** [comment]
建议1. 检查一下是不是双击保存设置了 2.去设置文件中检查是不是开启了每次打开用默认设置覆盖挂件设置

**Comment by OpaqueGlass** [comment]
大概率是没有双击刷新按钮保存设置。如果是这个原因，请考虑看一下README.md（或集市下载页）。

如果已经尝试双击保存，麻烦双击后关闭、重新打开文档看看是否正常。

**Comment by loudawang** [comment]
问题已解决，感谢。
已通过双击刷新按钮保存了。-未看说明，错过了这一点。
