### ISSUE TITLE
支持设置最大子文档数量&设定排序方式

### ISSUE THREAD

**Issue by GuangDai** [OpaqueGlass/listChildDocs#37]
你好，非常感谢你的插件给我提供了很好的帮助。
但是我遇到了一个问题：挂件的子文档数量是受到文档树中“最大列出数量”的影响。文档树中最多30条，那么挂件中也只能最多30条。
这个和我本身希望的场景并不是那么相符。因为在一个目录下我有远不止30个文档，如果在文档树中全部显示就会影响文档树的阅读效率，而在挂件中显示就会好很多。
请问能否根据自己的需求去修改这个设置？我已阅读代码，但由于我对JS不熟悉，并没有头绪修改，如果作者没时间修改，请指出相关实现的代码段落，我会自己想办法改改。还请麻烦作者了。

**Comment by OpaqueGlass** [comment]
抱歉，目前挂件通过文档树API获取下方的子文档信息，因而受限于文档树API的子文档数量限制；

可能的解决方案：
1. 重写挂件的listChildDocsMain.js下的`getText()` `getTextFromNotebooks()`  `getOneLevelText()`函数，改为使用sql查询子文档，代价是不能显示文档图标、可能与文档树顺序不同；
2. 在listChildDocsClass.js里继承Printer自定义一个新模式，重写`doGenerate()`以使用sql查询；
3. 向思源提供PR，修改`kernel/model/file.go`下的`ListDocTree` ([可能的代码行](https://github.com/siyuan-note/siyuan/blob/a1e389df19df35e81bf3ae1cb4fb72d2e1c30857/kernel/model/file.go#L342)，另外，可能还包括其他调用此函数的代码)，以支持传入Conf.FileTree.MaxListCount值；

我暂时无计划着手更改，实在需要的话，需要您自己修改代码。

**Comment by GuangDai** [comment]
> 抱歉，目前挂件通过文档树API获取下方的子文档信息，因而受限于文档树API的子文档数量限制；
> 
> 可能的解决方案：
> 
>     1. 重写挂件的listChildDocsMain.js下的`getText()` `getTextFromNotebooks()`  `getOneLevelText()`函数，改为使用sql查询子文档，代价是不能显示文档图标、可能与文档树顺序不同；
> 
>     2. 在listChildDocsClass.js里继承Printer自定义一个新模式，重写`doGenerate()`以使用sql查询；
> 
>     3. 向思源提供PR，修改`kernel/model/file.go`下的`ListDocTree` ([可能的代码行](https://github.com/siyuan-note/siyuan/blob/a1e389df19df35e81bf3ae1cb4fb72d2e1c30857/kernel/model/file.go#L342)，另外，可能还包括其他调用此函数的代码)，以支持传入Conf.FileTree.MaxListCount值；
> 
> 
> 我暂时无计划着手更改，实在需要的话，需要您自己修改代码。

好的，API的问题我已经提交给D大他们，D大说在新的版本发布中会加入一个可选参数进行设置，之后我会自己先修改一下API.js文件。实在不懂JS和怎么写一个页面布局，估计没办法提交PR了。谢谢你的回复。

**Comment by OpaqueGlass** [comment]
好的，思源新版本发布后我也会尽快在挂件里加入该设置。
