### ISSUE TITLE
代码移除`?.`、`replaceAll`等以支持旧版Webview

### ISSUE THREAD

**Issue by xylyp** [OpaqueGlass/listChildDocs#38]
该挂件在手机端思源笔记app插入后不显示。只在电脑中显示，希望大佬空闲之余能不能改进 一下，谢谢大佬！

**Comment by OpaqueGlass** [comment]
感谢反馈，请问使用的是苹果设备吗？挂件是完全不显示吗？
目前已知的是安卓端正常，之前只在iPad上出现过无法显示的问题，这个问题暂时无法定位（因为在sarifi浏览器中一切正常，并且复现方式不明确），在多次同步后似乎会解决。

可能需要您帮助确认：
使用手机浏览器，在思源运行的情况下打开127.0.0.1:6806，然后检查挂件是否能正常显示。

**Comment by xylyp** [comment]
谢谢大佬，那可能是我手机问题，我手机上插件点设置或者刷新都没反应，用手机浏览器打开网络伺服也不显示，但是用电脑浏览器打开网络伺服就显示了，手机端是最新的app和挂件。
![Screenshot_20230508085055](https://user-images.githubusercontent.com/132681338/236711842-55233032-bbf2-40cf-88b5-40912a1152fc.jpg)

**Comment by xylyp** [comment]
![Screenshot_20230508085055](https://user-images.githubusercontent.com/132681338/236711895-fc35e260-ec6c-44a6-af80-815495e34f31.jpg)
谢谢大佬，估计是我手机问题。用手机浏览器打开网络伺服也不显示，但是用电脑浏览器打开网络伺服却显示，说明挂件正常，app和挂件都是最新版的，主题用的saver。

**Comment by OpaqueGlass** [comment]
手边有个旧手机，大概检查了一下，挂件代码中使用`?.`（可选链运算符）语法在旧版本的设备上不支持，您那边可能也是这个原因；
可以的话升级一下系统。

另外，我也尽量在下个版本修改这些不兼容的地方

**Comment by xylyp** [comment]
![a35e965e30c85412208f41bd038fa5c](https://user-images.githubusercontent.com/132681338/236722651-960c964c-3dde-4c11-a5e1-00bc6a9387e0.jpg)
好的，谢谢大佬，确实是旧手机了，不过我喜欢用电脑浏览器打开网络伺服，影响不大。谢谢大佬的回复了

**Comment by xylyp** [comment]
![(D9W_I`VKS4SOH}8SQB $MD](https://user-images.githubusercontent.com/132681338/236725345-fa2b5a06-0216-44af-8c30-82b854a082d7.png)
![KU0ZUHRKNP{K%QQ)(BXNES7](https://user-images.githubusercontent.com/132681338/236725522-37054c87-9376-4a33-b1a2-5da45493aeda.jpg)

![d82f9aaf0beac018e8473b1a9b6f8e7](https://user-images.githubusercontent.com/132681338/236725498-e9c6e0ce-1421-4dc3-a04d-fdce178b32ae.jpg)

QQ三群有个大佬给了一个zhe折衷的方案很适合我，在电脑浏览器list插件设置里第一次选划圈的那几个就行了，解决了，也谢谢大佬写的挂件。省了好多事。

**Comment by OpaqueGlass** [comment]
把子文档列表插入文档的话，也可以直接用其他大佬开发的插件，这样文档里就没有碍事的挂件了
![image](https://user-images.githubusercontent.com/52985952/236727254-47997756-11ba-4c1b-bcf2-6999662e34ae.png)

**Comment by xylyp** [comment]
不会碍事，大佬你的这个插件这样正好，因为我手机一般不编辑，都是用电脑浏览器编辑，电脑上正常，谢谢大佬了，这个问题解决了。

**Comment by OpaqueGlass** [comment]
抱歉拖得有点久，已经在v0.2.1中尝试修复这个问题，您可以更新看看。

**Comment by OpaqueGlass** [comment]
由于您长时间没有回复，此issue将被关闭。感谢反馈。
