### ISSUE TITLE
重建索引后，显示“错误：查询当前文档所属路径失败，请稍后刷新重试。”

### ISSUE THREAD

**Issue by joetin** [OpaqueGlass/listChildDocs#39]
思源版本：windows 2.9.1
挂件版本：0.2.1
问题：在有挂件的页面点重建索引后，出现“错误：查询当前文档所属路径失败，请稍后刷新重试。”挂件恢复初始大小，但挂件设置保留。再次点击刷新后恢复正常，但挂件大小还是需要再次手动调节。

**Comment by OpaqueGlass** [comment]
烦请在v0.2.2版中再进行尝试，谢谢。
