### ISSUE TITLE
排序有问题

### ISSUE THREAD

**Issue by GuangDai** [OpaqueGlass/listChildDocs#42]
这个是官方代码部分的排序模式
![image](https://github.com/OpaqueGlass/listChildDocs/assets/59678726/dd279265-bac0-424f-9f06-34ee4c766df9)

![image](https://github.com/OpaqueGlass/listChildDocs/assets/59678726/d318b953-e177-47c1-b33c-cbacd7e14461)

然后在插件请求中 sort参数是字符串类型：
![image](https://github.com/OpaqueGlass/listChildDocs/assets/59678726/4d281524-3f24-4883-9a79-9ffbfe71b624)
导致请求返回的是404，不存在

而在curl中改成数字，就没有问题了，所以需要在这里修改一下
![image](https://github.com/OpaqueGlass/listChildDocs/assets/59678726/21d75a62-f97e-4544-bea7-e114086eef44)

**Comment by GuangDai** [comment]
我在代码里面粗暴的加了一下Number(sort)

![image](https://github.com/OpaqueGlass/listChildDocs/assets/59678726/4ef31e16-10f9-47ef-838f-1fd3b21cf451)

现在就没有这个问题了，这个方法都是现搜的字符串转数字，我不懂JS，所以很抱歉不能提交一个合格的PR

**Comment by OpaqueGlass** [comment]
哦哦，感谢反馈；其实粗暴地加个Number(sort)也挺好的😂我也不会js

**Comment by OpaqueGlass** [comment]
属实是加了一堆自己都不用的功能，然后也懒得测试所有功能😂。

**Comment by OpaqueGlass** [comment]
已经在集市更新，感谢反馈。
