### ISSUE TITLE
隐藏按钮后怎么在进入设置

### ISSUE THREAD

**Issue by sfdzkj** [OpaqueGlass/listChildDocs#46]
上边的按钮隐藏掉了。找不到重新进入设置的地方了

**Comment by OpaqueGlass** [comment]
> 点一下挂件的空白部分，按Ctrl + S；（其他还有F5刷新，Ctrl+F搜索）
当时只是在“显示按钮栏”选项右边的提示里加了个快捷键说明，但README没写（今天刚想到这个提示不明显，也没人反馈过，我以为没啥大碍，😂）

已更新README，加入了快捷键的说明；感谢反馈。
