### ISSUE TITLE
Errors happens in every page which contains this widget

### ISSUE THREAD

**Issue by STMRabbit** [OpaqueGlass/listChildDocs#47]
Hello, it seems there are errors reported in console, in every page which contains this widget
![image](https://github.com/OpaqueGlass/listChildDocs/assets/112855065/6efd2f02-6339-4200-9432-7ae91db5b785)

I tried to create a new workspace and only use this widget to test, and the errors are still there.

and here is the entire err message:
```
GET http://127.0.0.1:35879/widgets/custom.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ VM576 config.js:539
listChildDocs/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:35879/widgets/custom.js
Promise.then (async)
(anonymous) @ VM576 config.js:539
:35879/widgets/listChildDocs/:1 Uncaught TypeError: Failed to fetch
config.js:539 
        
        
       GET http://127.0.0.1:35879/widgets/custom.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ config.js:539
index_en.html:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:35879/widgets/custom.js
Promise.then (async)
(anonymous) @ config.js:539

```
Thank you!

**Comment by OpaqueGlass** [comment]
I will fix this in next version, thank you for your feedback.

> In the version earlier than v0.2.2, the widget would load user default settings from the `custom.js` file even if the file does not exist. That's why it always reported this error. In version v0.2.2, all default data has been moved to `/data/storage/listChildDocs`. To transfer those settings, this loading script is still present. I will remove that code and other redundant logs in the next version.

**Comment by STMRabbit** [comment]
Thank you very much!

**Comment by OpaqueGlass** [comment]
If the problem still exists, or if other problems occur, please provide feedback at your convenience. Thank you very much. I will close this issue (may be temporarily).

**Comment by STMRabbit** [comment]
Hello, thank you so much for the work! The error msg indeed reduced, but there seems still one left.  
```
GET http://127.0.0.1:36015/widgets/custom.js net::ERR_ABORTED 404 (Not Found)
loadGlobalConfig @ ConfigManager.js:380
await in loadGlobalConfig (async)
loadAll @ ConfigManager.js:190
__init__ @ listChildDocsMainV2.js:1012
await in __init__ (async)
(anonymous) @ listChildDocsMainV2.js:1787
```

Here is what I did:
1. Update SiYuan to the latest ver. 
2. Create a new blank workspace.
3. Go to market and download v0.2.5 which released in Dec. 10 2023.
4. Create some docs to test. 

Maybe that's because I'm running SiYuan on openSUSE + GNOME? If so, then maybe don't worry about it, since I believe most users are using windows, so it won't hurt much. And to me, I didn't see any bad things happens, only an error msg which doesn't matters.   
Thank you again!

**Comment by OpaqueGlass** [comment]
It's my fault. I didn't completely remove the related codes. Please try [this version](https://github.com/OpaqueGlass/listChildDocs/releases/tag/v0.2.6-beta1) or click the save button in the Global Settings of widget (Since the global settings have been set, widget won't try to find that file.).

**Comment by STMRabbit** [comment]
Thank you so much! This issue seems resolved. Thank you again!
